Dictionary:





---

- name: test playbook
  hosts: routers



  vars:
    cli:
    	host: "{{ inventory_hostname }}"
    	username: test_user
    	password: test_password




  tasks:
    - name: test-task
      ios_config:
        backup: yes
      	providers: "{{ cli }}" 





-----------------------------------------------
Dictionary:





- name: test playbook
  hosts: routers



  vars:
    var_dic:
      name: hamid
      family: hosseinzadeh
      company: Internet




  tasks:
    - name: test-task1
      debug:
        msg: "{{ var.var_dic.name }}"




    - name: test-task2
      debug:
        msg: "{{ var.var_dic[name] }}"




    - name: test-task3
      debug:
        msg: "key is {{ item.key }} and value is {{ item.value }}"
      loop:
        - "{{ var_dic|dic2items }}"








-----------------------------------------------
String:




---

- name: test playbook
  hosts: routers



  backup_root: ./backup




  tasks:
    - name: ensure that Backup folder is created
      file:
        path: "{{ backup_root }}/myfiles"







-----------------------------------------------
Integer:





---

- name: test playbook
  hosts: routers



  var_int: 7




  tasks:
    - name: test-task
      debug:
        msg: "{{ var_int * 1.5 }}"






-----------------------------------------------
List:





---

- name: test playbook
  hosts: routers



  var_list:
    - my_first_item_of_my_list
    - my_second_item_of_my_list
    - my_third_item_of_my_list




  tasks:
    - name: test-task1
      debug:
        msg: "{{ var_list[0] }}"





    - name: test-task2
      debug:
        msg: "{{ item }}"

      loop:
        - "{{ var_list }}"





    - name: test-task3
      debug:
        msg: "{{ var_int * 1.5 }}"




-----------------------------------------------
vars_files:





---

- name: test playbook
  hosts: routers


  vars_files:
    - ./credendial.yaml




  tasks:
    - name: test-task
      ios_config:
        backup: yes
        providers: "{{ cli }}" 













./credendial.yaml


cli:
  host: "{{ inventory_hostname }}"
  username: test_user
  password: test_password






-----------------------------------------------
vars_prompt:






---
- hosts: routers
  vars_prompt:

    - name: username
      prompt: What is your username?
      private: no
      default: hamid

    - name: password
      prompt: What is your password?

  tasks:

    - name: Print a message
      ansible.builtin.debug:
        msg: 'Logging in as {{ username }}'








-----------------------------------------------





variable in the command line:

 ▶ ansicle-playbook myplaybook.yaml -e "username='hamid'"




-----------------------------------------------
a single var file for each host:









---

- name: test playbook
  hosts: routers

  include_vars: "{{ansible-hostname}}.yaml"

  vars:
    cli:
      host: "{{ inventory_hostname }}"
      username: test_user
      password: test_password




  tasks:
    - name: test-task
      ios_config:
        backup: yes
        providers: "{{ cli }}" 







r1.yaml
r2.yaml







-----------------------------------------------
Create a file for each group:




  group_vars
  ├── all
  ├── routers
  └── servers





-----------------------------------------------
Create a file for each host:





host_vars
├── r1
└── r2






-----------------------------------------------





