---

- name: error handler
  hosts: r1

  tasks:
    - name: execute a wrong command
      ios_command:
         commands: sho ip int brrr
      register: output
      ignore_errors: true

    - name: print output
      debug:
        var: output
      when: output is failed

















      when: output is succeed









_-------------------------------------------------_




    when: ansible_selinux.status == "enabled"

    when: ansible_facts['os_family'] == "Debian"



_-------------------------------------------------_



OR:

    - name: print output
      debug:
        var: output
      when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "6") or
            (ansible_facts['distribution'] == "Debian" and ansible_facts['distribution_major_version'] == "7")




AND:

    - name: print output
      debug:
        var: output
      when:
      - ansible_facts['distribution'] == "CentOS"
      - ansible_facts['distribution_major_version'] == "6"



_-------------------------------------------------_





if ths task is failed, go to nest task

      ignore_errors: true




_-------------------------------------------------_





---

- name: error handler
  hosts: r1

  tasks:
    - name: execute a wrong command
      ios_command:
         commands: sho ip int brrr
      register: output

    - name: print output
      msg: "your config is failed."