---
galaxy_info:
  author: Nick Lalumiere
  description: "Adds the ability for Ansible to backup Cisco Devices"
  role_name: cisco_backup
  license: GPLv3
  min_ansible_version: 2.4
  min_ansible_container_version: 0.2.0

  platforms:
    - name: Alpine
      versions:
        - all
    - name: ArchLinux
      version:
        - all
    - name: CentOS
      version:
        - 6
        - 7
    - name: Debian
      versions:
        - all
    - name: EL
      version:
        - 6
        - 7
    - name: Fedora
      versions:
        - all
    - name: OpenSUSE
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - backup
    - cisco
    - ci
    - cd

dependencies: []
